define('two/farmOverflow/settings', [], function () {
    return {
        PRESETS: 'presets',
        GROUP_IGNORE: 'group_ignore',
        GROUP_INCLUDE: 'group_include',
        GROUP_ONLY: 'group_only',
        MAX_DISTANCE: 'max_distance',
        MIN_DISTANCE: 'min_distance',
        IGNORE_FULL_STORAGE: 'ignore_full_storage',        
        RANDOM_BASE: 'random_base',
        MAX_TRAVEL_TIME: 'max_travel_time',
        TARGET_SINGLE_ATTACK: 'target_single_attack',
        TARGET_MULTIPLE_FARMERS: 'target_multiple_farmers',
        PRESERVE_COMMAND_SLOTS: 'preserve_command_slots',
        FARMER_CYCLE_INTERVAL: 'farmer_cycle_interval',
        MIN_POINTS: 'min_points',
        MAX_POINTS: 'max_points',
        LOGS_LIMIT: 'logs_limit',
        // PRIORITY_TARGETS: 'priority_targets',
        // IGNORE_ON_LOSS: 'ignore_on_loss',
        // STEP_CYCLE: 'step_cycle',
        // STEP_CYCLE_NOTIFS: 'step_cycle_notifs',
        // STEP_CYCLE_INTERVAL: 'step_cycle_interval',
        // EVENT_ATTACK: 'event_attack',
        // EVENT_VILLAGE_CHANGE: 'event_village_change',
        // EVENT_PRIORITY_ADD: 'event_priority_add',
        // EVENT_IGNORED_VILLAGE: 'event_ignored_village',
        // REMOTE_ID: 'remote_id',
        // HOTKEY_SWITCH: 'hotkey_switch',
        // HOTKEY_WINDOW: 'hotkey_window'
    }
})
